### ISSUE TITLE
Warning in logs when synchronizer updates empty segment

### ISSUE THREAD

**Issue by fyber** [splitio/split-synchronizer#102]
Just noticed the following line in `splitio-synchronizer` logs:

    SPLITIO-AGENT | WARNING: 2019/11/04 11:45:18 common.go:221: Error fetching last update for segment <<segment name>>

Opened that segment in Split.io dashboard and it turns out that it is just an empty segment (exists but contains no keys).
I understand that an empty segment looks a bit strange, but I think it's a normal situation, no need to issue Warning in logs.

`splitio-synchronizer` is version 2.5.2, running via an official docker image.

**Comment by mredolatti** [comment]
Hi @fyber , Thanks for reaching out. We apologize for any inconveniences caused. 
Can you contact us at support@split.io? You will be asked a couple of questions in order to debug this scenario, since it doesn't look like something that should happen, even for segments with no keys.

Thank you very much,
Martin.

**Comment by mmelograno** [comment]
Hi @fyber. First of all, sorry for the delay on fixing the unexpected behaviour. A new version of Split Sync (2.6.2) has been released that fixes that issue. 

Thanks,
Matias
