### ISSUE TITLE
Empty /tmp/split-agent.log file

### ISSUE THREAD

**Issue by zachschultz** [splitio/split-synchronizer#71]
Hello, I'm running the Synchronizer with the following docker command:
```
docker run --rm --name split-synchronizer-proxy \
 -p 3000:3000 \
 -p 3010:3010 \
 -e SPLIT_SYNC_API_KEY="MY SPLIT API KEY HERE" \
 -e SPLIT_SYNC_PROXY="on" \
 -e SPLIT_SYNC_LOG_VERBOSE=true \
 -e SPLIT_SYNC_LOG_DEBUG=true \
 -e SPLIT_SYNC_LOG_STDOUT=true \
 -e SPLIT_SYNC_PROXY_SDK_APIKEYS="MY PROXY KEYS HERE" \
 splitsoftware/split-synchronizer
```

After successfully requesting a treatment from an app running the Split Java SDK client, I `exec`d into the docker container running the Synchronizer and expected to see some logs in `/tmp/split-agent.log` file, however, the file was empty. Are there any other steps necessary to get more logging to happen?

**Comment by mredolatti** [comment]
Hello @zachschultz, I beleive that since you're using `SPLIT_SYNC_LOG_STDOUT=true`, the logs are being sent to the standard output (in this case, your containers') instead of the file.
Since you enabled `SPLIT_SYNC_LOG_DEBUG`, you should be able to see full debug information by inspecting your containers output with `docker logs <CONTAINER_ID>`.

**Comment by zachschultz** [comment]
Thanks for your quick response! So I am tailing the docker stdout as well now, but I'm still never getting any more logs than the intro:

```
Running in PROXY mode

     __      ____        _ _ _
    / /__   / ___| _ __ | (_) |_
   / / \ \  \___ \| '_ \| | | __|
   \ \  \ \  ___) | |_) | | | |_
    \_\ / / |____/| .__/|_|_|\__|
       /_/        |_|



Split Synchronizer - Version: 2.3.0 (e752118)
Log file: /logging.log
DB PATH: /tmp/splitio_1561147530007108000.db
```

With VERBOSE/DEBUG logging, should I expect to see each request from the Split Client in the docker logs?

**Comment by mredolatti** [comment]
@zachschultz Sorry I missed this in the previous answer, `SPLIT_SYNC_LOG_VERBOSE`, `SPLIT_SYNC_LOG_DEBUG` & `SPLIT_SYNC_LOG_STDOUT` are all enabled when assigned the value "on", as you've done with `SPLIT_SYNC_PROXY`

so doing:

```
docker run --rm --name split-synchronizer-proxy \
 -p 3000:3000 \
 -p 3010:3010 \
 -e SPLIT_SYNC_API_KEY="MY SPLIT API KEY HERE" \
 -e SPLIT_SYNC_PROXY="on" \
 -e SPLIT_SYNC_LOG_VERBOSE="on" \
 -e SPLIT_SYNC_LOG_DEBUG="on" \
 -e SPLIT_SYNC_LOG_STDOUT="on" \
 -e SPLIT_SYNC_PROXY_SDK_APIKEYS="MY PROXY KEYS HERE" \
 splitsoftware/split-synchronizer
```
Should behave as expected.

My apologies for this since I know it's confusing, we're currently working on improving it by supporting other `true` values as well and possibly notifying if an invalid value is found.

Thank you very much for reaching out.
Regards,

Martin.

**Comment by zachschultz** [comment]
heh that definitely did the trick! Thank you very much for your help!
